name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Pack Common
      run: dotnet pack src/Packages/CoreArk.Packages.Common/CoreArk.Packages.Common.csproj --output nuget-packages --configuration Release
    - name: Pack Core
      run: dotnet pack src/Packages/CoreArk.Packages.Core/CoreArk.Packages.Core.csproj --output nuget-packages --configuration Release
    - name: Pack Exceptions
      run: dotnet pack src/Packages/CoreArk.Packages.Exceptions/CoreArk.Packages.Exceptions.csproj --output nuget-packages --configuration Release
    - name: Pack Models
      run: dotnet pack src/Packages/CoreArk.Packages.Models/CoreArk.Packages.Models.csproj --output nuget-packages --configuration Release
    - name: Pack Security
      run: dotnet pack src/Packages/CoreArk.Packages.Security/CoreArk.Packages.Security.csproj --output nuget-packages --configuration Release
    - name: Pack Services
      run: dotnet pack src/Packages/CoreArk.Packages.Services/CoreArk.Packages.Services.csproj --output nuget-packages --configuration Release
    - name: Pack Web
      run: dotnet pack src/Packages/CoreArk.Packages.Web/CoreArk.Packages.Web.csproj --output nuget-packages --configuration Release
    - name: Push with dotnet
      run: dotnet nuget push nuget-packages/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json

